const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
    .use(express.static(path.join(__dirname, 'public')))
    .set('views', path.join(__dirname, 'views'))
    .set('view engine', 'ejs')
    .get('/', (req, res) => res.render('pages/index'))
	.get('/math', (req, res) => res.render('pages/math'))
	.get('/math/variables', (req, res) => res.render('pages/Mvariables'))
	.get('/math/calculator', (req, res) => res.render('pages/Mcalculator'))
	.get('/math/graphAngleRule', (req, res) => res.render('pages/MgraphAngleRule'))
	.get('/physics', (req, res) => res.render('pages/physics'))
	.get('/physics/variables', (req, res) => res.render('pages/Pvariables'))
	.get('/physics/laws', (req, res) => res.render('pages/Plaws'))
	.get('/physics/curcuits', (req, res) => res.render('pages/Pcurcuits'))
	.get('/chemistry', (req, res) => res.render('pages/chemistry'))
	.get('/chemistry/variables', (req, res) => res.render('pages/Cvariables'))
	.get('/chemistry/table', (req, res) => res.render('pages/Ctables'))
	.get('/chemistry/redox', (req, res) => res.render('pages/Credox'))
    .listen(PORT, () => console.log(`Listening on ${ PORT }`))