const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
    .use(express.static(path.join(__dirname, 'public')))
    .set('views', path.join(__dirname, 'views'))
    .set('view engine', 'ejs')
    .get('/', (req, res) => res.render('pages/index'))
	.get('/math', (req, res) => res.render('pages/math'))
	.get('/math/variables', (req, res) => res.render('pages/variables'))
	.get('/math/calculator', (req, res) => res.render('pages/calculator'))
	.get('/math/graphAngleRule', (req, res) => res.render('pages/graphAngleRule'))
	.get('/physics', (req, res) => res.render('pages/physics'))
	.get('/chemistry', (req, res) => res.render('pages/chemistry'))
    .listen(PORT, () => console.log(`Listening on ${ PORT }`))